WorkShop2/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace WorkShop2.Controllers
{
    public class LibraryController : Controller
    {
        // GET: Library
        Models.CodeService codeService = new Models.CodeService();
        private string DBstr()
        {
            return System.Configuration.ConfigurationManager.ConnectionStrings["Contact"].ConnectionString.ToString();
        }

        public ActionResult Index()
        {
            DataTable data = new DataTable();
            SqlConnection conn = new SqlConnection(DBstr());
            String sql = "Select [dbo].[BOOK_DATA].BOOK_ID, [dbo].[BOOK_DATA].BOOK_NAME, [dbo].[BOOK_CLASS].BOOK_CLASS_NAME, [dbo].[BOOK_DATA].BOOK_AUTHOR, [dbo].[CODE].CODE_NAME, [dbo].[MEMBER].USER_NAME" +
                         " From [dbo].[BOOK_DATA]" +
                         " LEFT JOIN [dbo].[MEMBER] ON [dbo].[MEMBER].USER_ID = [dbo].[BOOK_DATA].BOOK_KEEPER" +
                         " LEFT JOIN [dbo].[CODE] ON [dbo].[CODE].CODE_ID = [dbo].[BOOK_DATA].BOOK_STATUS" +
                         " LEFT JOIN [dbo].[BOOK_CLASS] ON [dbo].[BOOK_CLASS].BOOK_CLASS_ID = [dbo].[BOOK_DATA].BOOK_CLASS_ID";
            SqlCommand scm = new SqlCommand(sql, conn);
            SqlDataAdapter adapter = new SqlDataAdapter(scm); //連接db
            DataSet dataSet = new DataSet();
            adapter.Fill(dataSet, "data");

            string str_json = JsonConvert.SerializeObject(dataSet, new DataTableConverter());
            String json = GetJson(dataSet);
            ViewBag.jstr = json;
            return View(dataSet);
        }

        public string GetJson(DataSet ds) //轉Json
        {
            System.Web.Script.Serialization.JavaScriptSerializer serializer = new
            System.Web.Script.Serialization.JavaScriptSerializer();
            List<Dictionary<object, object>> rows = new List<Dictionary<object, object>>();
            Dictionary<object, object> row;
            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                row = new Dictionary<object, object>();
                foreach (DataColumn col in ds.Tables[0].Columns)
                {
                    row.Add(col.ColumnName, dr[col]);
                }
                rows.Add(row);
            }
            return serializer.Serialize(rows);
        }

        [HttpGet()]
        public ActionResult Insert() //新增畫面
        {
            ViewBag.BookNameCodeData = this.codeService.GetCodeTable("BOOKNAME");
            ViewBag.AuthorCodeData = this.codeService.GetCodeTable("AUTHOR");
            ViewBag.PublisherCodeData = this.codeService.GetCodeTable("PUBLISHER");
            ViewBag.EmpCodeData = this.codeService.GetBook("0");
            return View(new Models.Book());
        }

        [HttpPost()]
        public ActionResult Insert(Models.Book book)
        {
            ViewBag.BookNameCodeData = this.codeService.GetCodeTable("BOOKNAME");
            ViewBag.AuthorCodeData = this.codeService.GetCodeTable("AUTHOR");
            ViewBag.PublisherCodeData = this.codeService.GetCodeTable("PUBLISHER");
            ViewBag.EmpCodeData = this.codeService.GetBook("0");
            if (ModelState.IsValid)
            {
                Models.BookService bookService = new Models.BookService();
                if (book.BookName != null)
                    book.BookName = book.BookName.Replace(",", "");
                if (book.ClassId != null)
                    book.ClassId = book.ClassId.Replace(",", "");
                bookService.Insert(book);
                TempData["message"] = "存檔成功";
            }
            return View(book);
        }

        [HttpPost()]
        public ActionResult Search(Models.BookArg barg) //查詢
        {
            Models.BookService bookService = new Models.BookService();
            ViewBag.SearchResult = bookService.GetBookByCondition(barg);
            ViewBag.BookNameCodeData = this.codeService.GetCodeTable("BOOKNAME");
            return View("Search");
        }

        [HttpPost()]
        public JsonResult Delete(string bookId)
        {
            try
            {
                Models.BookService bookService = new Models.BookService();
                bookService.DeleteBook(bookId);
                return this.Json(true);
            }
            catch (Exception ex)
            {
                return this.Json(false);
            }
        }

        public ActionResult Update(string bookId)
        {
            Models.BookService bookService = new Models.BookService();
            bookService.Update(bookId);
            return View("Update");
        }
    }
}

WorkShop2/Views/Library/Index.cshtml
@using System.Data
@model System.Data.DataSet

@{
    /**/

    ViewBag.Title = "Index";
}
<head>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.bootstrap-v4.min.css" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <link rel="stylesheet" href="http://kendo.cdn.telerik.com/2019.2.514/styles/kendo.common.min.css" />
    <link rel="stylesheet" href="http://kendo.cdn.telerik.com/2019.2.514/styles/kendo.blueopal.min.css" />
    <script src="http://kendo.cdn.telerik.com/2019.2.514/js/jquery.min.js"></script>

    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.all.min.js"></script>
</head>


<h2>查詢書籍</h2>
@using (Html.BeginForm("Insert", "Library", FormMethod.Post))
{
    <div align="center">
        書籍名稱 <input type="text" class="k-textbox" /><br />
        書籍類別 <select id="category">
            <option>Comics</option>
            <option>DataBase</option>
            <option>Finance</option>
            <option>Program</option>
        </select><br />
        現保管人 <select id="memeber">
            <option>Jenny</option>
            <option>Jessica</option>
            <option>Sam</option>
            <option>Elsa</option>
        </select><br />
        書籍狀態 <select id="status">
            <option>可租借</option>
            <option>不可租</option>
            <option>不可借</option>
            <option>已租未領</option>
        </select><br />
        <input type="submit" value="新增" id="insert" class="btn btn-warning" onclick='this.form.action="Insert"' />
        <input type="submit" value="查詢" id="search" class="btn btn-success" onclick='this.form.action="Search"' />
        <span class="btn btn-info">清除</span>
    </div>

    <script>$("#category").kendoDropDownList();</script>
    <script>$("#memeber").kendoDropDownList();</script>
    <script>$("#status").kendoDropDownList();</script>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>書籍編號</th>
                <th>書籍名稱</th>
                <th>書籍種類</th>
                <th>作者</th>
                <th>狀態</th>
                <th>保管者</th>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (DataRow row in Model.Tables[0].Rows)
            {
            <tr>
                <td>@row["BOOK_ID"]</td>
                <td>@row["BOOK_NAME"]</td>
                <td>@row["BOOK_CLASS_NAME"]</td>
                <td>@row["BOOK_AUTHOR"]</td>
                <td>@row["CODE_NAME"]</td>
                <td>@row["USER_NAME"]</td>
                <td>@Html.ActionLink("修改", "Update", new { id = @row["BOOK_ID"] })</td>
                <td>
                    <a class="delete" href="#" onclick="test(this,'@row["BOOK_ID"]');">刪除</a>
                    <input class="hidId" type="hidden" value='@row["BOOK_ID"]' />
                </td>
            </tr>
            }
        </tbody>
    </table>

    <div id="grid">Grid</div>
}


<script type="text/javascript">
    $(document).ready(function () { //表單
        var dataSource = new kendo.data.DataSource({
            data: @ViewBag.jstr,
            pageable:10
        });
        $("#grid").kendoGrid({
            dataSource: dataSource,
            pageable: true
        });

        var myWindow = $("#Insertwindow"), //Kendowindow
            insert = $("#insert");

        insert.click(function () {
            myWindow.data("kendoWindow").open();
            insert.fadeOut();
        });

        myWindow.kendoWindow({
            width: "600px",
            height: "700px",
            title: "新增書籍",
            visible: false,
            actions: [
                "Pin",
                "Minimize",
                "Maximize",
                "Close"
            ],
            close: onClose
        }).data("kendoWindow").center().open();

        $(".delete").click(function (e) { //刪除
            e.preventDefault();
            var tr = $(this).closest('tr')
            $.ajax({
                type: "POST",
                url: "/Library/Delete",
                data: "bookId=" + $(this).next().val(),
                dataType: "json",
                success: function (response) {
                    $(tr).remove();
                }, error: function (error) {
                    alert("系統發生錯誤");
                }
            });
            return false;
        });
    });
</script>

WorkShop2/Views/Library/Insert.cshtml
@model WorkShop2.Models.Book

@{
    ViewBag.Title = "Insert";
}

<head>
    <link rel="stylesheet" href="http://kendo.cdn.telerik.com/2019.2.514/styles/kendo.common.min.css" />
    <link rel="stylesheet" href="http://kendo.cdn.telerik.com/2019.2.514/styles/kendo.blueopal.min.css" />

    <script src="http://kendo.cdn.telerik.com/2019.2.514/js/jquery.min.js"></script>
</head>

<h2>新增頁面</h2>
<div id="Insertwindow">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BookName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BookName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BookName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ClassId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ClassId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ClassId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BoughtDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BoughtDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BoughtDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Publisher, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Publisher, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Publisher, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Keeper, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Keeper, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Keeper, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="新增" id="InsertClose" class="btn btn-info" />
                    <input type="button" value="回首頁" class="btn btn-warning" onclick="location.href='http://localhost:7728/Library/Index'">
                </div>
            </div>
        </div>

    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var myWindow = $("#Insertwindow");
        $("#InsertClose").click(function (e) {
            myWindow.data("kendoWindow").close();
        });
        myWindow.kendoWindow({
            width: "600px",
            height: "700px",
            title: "新增書籍",
            visible: false,
            actions: [
                "Pin",
                "Minimize",
                "Maximize",
                "Close"
            ],
        }).data("kendoWindow").center().open(); 
    });
</script>

WorkShop2/Views/Library/Search.cshtml
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

@if (ViewBag.SearchResult != null)
{
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>書籍名稱</th>
                <th>種類編號</th>
                <th>書籍狀態</th>
                <th>保管人</th>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in (List<WorkShop2.Models.Book>)ViewBag.SearchResult)
            {
                <tr id='@item.Id'>
                    <td>@item.BookName</td>
                    <td>@item.ClassId</td>
                    <td>@item.Status</td>
                    <td>@item.Keeper</td>
                    <td>@Html.ActionLink("修改", "UpdateEmployee", new { id = item.Id })</td>
                    <td>
                        <a class="btnDelete" href="#" onclick="test(this,'@item.Id');">刪除</a>
                        <input class="hidEmployeeId" type="hidden" value='@item.Id' />
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

WorkShop2/Views/Library/Update.cshtml
@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>